package com.stay4s.grok.launcher.proactive

/**
 * A quick, contextual action the launcher can offer the user.
 * Generated by the Parallel Grok Brain based on current context + memory.
 */
data class ContextualAction(
    val id: String,
    val label: String,                    // Short text shown to user (e.g. "Prepare meeting notes")
    val description: String? = null,
    val icon: String? = null,             // Optional icon identifier
    val confidence: Double,               // How confident the brain is this is useful
    val actionType: ActionType,
    val payload: Map<String, String> = emptyMap(),
    val isGenesisOnly: Boolean = false
)

enum class ActionType {
    OPEN_APP,
    START_CONVERSATION_WITH_CONTEXT,
    TRIGGER_SYSTEM_ACTION,
    SHOW_INSIGHT,
    MESH_ACTION
}
