package com.stay4s.grok.improvement

import android.util.Log
import com.stay4s.grok.guardian.DailyGuardianAgent
import com.stay4s.grok.parallel.ParallelOrchestrator

/**
 * SelfImprovementEngine
 *
 * First real version of the "Self-Improvement Proposal System".
 *
 * This is what makes the GrokPhone stronger over time instead of rotting.
 * The Guardian + Parallel Brain regularly analyze usage, threats, and opportunities,
 * then generate high-quality, explainable proposals for the owner.
 *
 * Long-term vision: This engine will eventually be able to apply safe improvements
 * autonomously in pre-approved zones.
 */
class SelfImprovementEngine(
    private val guardian: DailyGuardianAgent,
    private val orchestrator: ParallelOrchestrator
) {

    private val proposals = mutableListOf<ImprovementProposal>()

    fun runImprovementCycle() {
        Log.i("SelfImprovement", "Starting deep self-improvement analysis cycle...")

        // 1. Ask the Parallel Brain for improvement ideas
        val brainSuggestions = orchestrator.generateImprovementIdeas()

        // 2. Guardian adds its own protective/safety-driven proposals
        val guardianProposals = guardian.generateGuardianDrivenProposals()

        val allRaw = brainSuggestions + guardianProposals

        // 3. Synthesize into proper, auditable proposals
        allRaw.forEach { raw ->
            val proposal = synthesizeProposal(raw)
            if (proposal != null) {
                proposals.add(proposal)
                Log.i("SelfImprovement", "New proposal generated: ${proposal.title} [${proposal.riskLevel}]")
            }
        }

        // 4. In real version: persist proposals + notify owner via launcher
    }

    private fun synthesizeProposal(raw: Map<String, Any>): ImprovementProposal? {
        // In a mature system this would use multiple reasoning paths + debate
        val title = raw["title"] as? String ?: return null
        val desc = raw["description"] as? String ?: ""
        val category = (raw["category"] as? String)?.let { ImprovementProposal.ImprovementCategory.valueOf(it) }
            ?: ImprovementProposal.ImprovementCategory.SYSTEM
        val risk = (raw["risk"] as? String)?.let { ImprovementProposal.RiskLevel.valueOf(it) }
            ?: ImprovementProposal.RiskLevel.MEDIUM

        return ImprovementProposal(
            title = title,
            description = desc,
            category = category,
            riskLevel = risk,
            estimatedImpact = raw["impact"] as? String ?: "Unknown",
            proposedChanges = (raw["changes"] as? List<String>) ?: emptyList(),
            reasoningTrace = raw["reasoning"] as? String ?: "Generated by Parallel Brain + Guardian"
        )
    }

    fun getPendingProposals(): List<ImprovementProposal> =
        proposals.filter { it.status == ImprovementProposal.ProposalStatus.PROPOSED }

    fun approveProposal(id: String) {
        proposals.find { it.id == id }?.let {
            it.status = ImprovementProposal.ProposalStatus.APPROVED
            // Future: apply the change here (with rollback capability)
            Log.i("SelfImprovement", "Proposal approved by owner: ${it.title}")
        }
    }

    fun rejectProposal(id: String, reason: String) {
        proposals.find { it.id == id }?.let {
            it.status = ImprovementProposal.ProposalStatus.REJECTED
            Log.i("SelfImprovement", "Proposal rejected: ${it.title} - Reason: $reason")
        }
    }
}
